export type PropertyStatus = 'draft' | 'active' | 'under_offer' | 'sold' | 'let'
export type Organization = { id: string; name: string; slug: string; logo_path: string | null; website: string | null; created_at: string }
export type Property = { id: string; organization_id: string; title: string; address: string; description: string; property_type: string; bedrooms: number; bathrooms: number; status: PropertyStatus; layout_width_m: number; created_at: string; updated_at: string }
export type LevelType = 'site' | 'ground' | 'upper' | 'basement' | 'roof_terrace' | 'custom'
export type Level = { id: string; property_id: string; name: string; level_type: LevelType; sort_order: number; elevation: number; canvas_width: number; canvas_height: number; geometry_mode?: 'legacy' | 'topology'; created_at: string }
export type SpaceCategory = 'indoor' | 'outdoor'
export type SpaceType = 'living_room' | 'bedroom' | 'kitchen' | 'bathroom' | 'dining_room' | 'corridor' | 'office' | 'store' | 'garage' | 'utility' | 'studio' | 'stairs' | 'building_footprint' | 'garden' | 'pool' | 'parking' | 'driveway' | 'patio' | 'terrace' | 'balcony' | 'porch' | 'yard' | 'other'
export type FloorPlan = { id: string; property_id: string; level_id: string; storage_path: string; width: number; height: number; created_at: string }
export type Room = { id: string; property_id: string; level_id: string; name: string; description: string; sort_order: number; space_type: SpaceType; category: SpaceCategory; height: number; created_at: string }
export type Space = Room
export type RoomMedia = { id: string; room_id: string; storage_path: string; alt_text: string; sort_order: number; created_at: string; url?: string }
export type Point = { x: number; y: number }
export type RoomPolygon = { id: string; floor_plan_id: string | null; level_id: string; room_id: string; points: Point[]; created_at: string }
export type OpeningType = 'standard_door' | 'double_door' | 'standard_window' | 'wide_window'
export type Opening = { id: string; space_id: string; polygon_id: string; opening_type: OpeningType; segment_index: number; position: number; width: number; height: number; sill_height: number; created_at: string }
export type StairType = 'straight' | 'l_shaped' | 'u_shaped' | 'spiral'
export type StairConnection = { id: string; space_id: string; destination_level_id: string; stair_type: StairType; created_at: string }
export type Tour = { id: string; property_id: string; slug: string; published: boolean; published_at: string | null; created_at: string }
export type Subscription = { organization_id: string; stripe_customer_id: string | null; stripe_subscription_id: string | null; stripe_price_id: string | null; plan: 'free' | 'professional'; status: string; current_period_end: string | null }
export type ProcessingJob = { id: string; property_id: string; status: 'queued' | 'processing' | 'completed' | 'failed'; progress: number; error_message: string | null; started_at: string | null; completed_at: string | null; created_at: string }
export type PropertyModel = { id: string; property_id: string; glb_path: string; scene_path: string; version: number; created_at: string; glb_url?: string; scene_url?: string }
export type ModelRoom = { id: string; name: string; level_id: string; category: SpaceCategory; center: [number, number, number]; camera_anchor: [number, number, number]; polygon: [number, number][]; photo_ids: string[] }
export type ModelScene = { schema_version: number; property_id: string; units: string; levels: { id: string; name: string; elevation: number }[]; rooms: ModelRoom[]; walls?: { id: string; level_id: string; kind: string; left_space_id: string | null; right_space_id: string | null }[]; site_edges?: { id: string; room_id: string; level_id: string; behavior: string; height: number }[]; stairs?: { id: string; source_level_id: string; destination_level_id: string; type: StairType; footprint: Point[]; step_count: number; rise_m: number; railing_height_m: number }[]; stairs_needing_review?: string[] }
export type TourPayload = { property: Property; organization: Organization & { logo_url?: string }; floor_plan: (FloorPlan & { url: string }) | null; floor_plans?: (FloorPlan & { url: string })[]; levels?: Level[]; rooms: (Room & { media: RoomMedia[] })[]; polygons: RoomPolygon[]; openings?: Opening[]; layout_graphs?: { level_id: string; graph: import('./topology').LayoutGraph }[]; stairs?: StairConnection[]; model?: PropertyModel | null; tour: Tour }
