import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, Building2, Plus, Search } from 'lucide-react'
import { useApp } from '../context'
import { listProperties } from '../lib/data'
import { errorMessage } from '../lib/supabase'
import type { Property } from '../lib/types'
import { Button, Card, Input, Notice, PageHeader, Spinner } from '../components/ui'
export function PropertiesPage() { const { organization } = useApp(); const [items, setItems] = useState<Property[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { if (!organization) return; setLoading(true); listProperties(organization.id).then(setItems).catch(e => setError(errorMessage(e))).finally(() => setLoading(false)) }, [organization]); const filtered = items.filter(item => `${item.title} ${item.address}`.toLowerCase().includes(search.toLowerCase())); return <><PageHeader eyebrow="Portfolio" title="Properties" description="Manage listings and build interactive tours for every property." action={<Button asChild><Link to="/properties/new"><Plus size={17}/>New property</Link></Button>} /><div className="mb-6 max-w-md"><div className="relative"><Search size={18} className="absolute left-3 top-3 text-slate-400"/><Input aria-label="Search properties" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search properties or addresses" className="pl-10" /></div></div>{error && <Notice>{error}</Notice>}{loading ? <Spinner /> : filtered.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map(p => <Link to={`/properties/${p.id}`} key={p.id} className="group"><Card className="h-full p-0 transition-transform hover:-translate-y-1"><div className="grid h-36 place-items-center rounded-t-2xl bg-gradient-to-br from-[#dae9df] to-[#b6d5cb]"><Building2 size={44} className="text-pine/40"/></div><div className="p-5"><div className="flex items-start justify-between gap-3"><h2 className="text-lg font-extrabold group-hover:text-pine">{p.title}</h2><ArrowRight size={19} className="shrink-0 text-pine"/></div><p className="mt-2 line-clamp-1 text-sm text-slate-500">{p.address}</p><div className="mt-5 flex items-center justify-between border-t border-line pt-4 text-xs"><span className="rounded-full bg-mint px-3 py-1 font-bold capitalize text-pine">{p.status.replace('_', ' ')}</span><span className="text-slate-400">{p.bedrooms} beds · {p.bathrooms} baths</span></div></div></Card></Link>)}</div> : <Card className="py-14 text-center"><Building2 className="mx-auto text-pine" size={34}/><h2 className="mt-4 text-lg font-extrabold">{search ? 'No matching properties' : 'No properties yet'}</h2><p className="mt-2 text-sm text-slate-500">{search ? 'Try a different search.' : 'Create your first listing to get started.'}</p>{!search && <Button asChild className="mt-5"><Link to="/properties/new">Create property</Link></Button>}</Card>}</> }
