import { useEffect, useRef, useState } from 'react'
import { Circle, Image as KonvaImage, Layer, Line, Stage, Text } from 'react-konva'
import type Konva from 'konva'
import type { Point, Room, RoomPolygon } from '../lib/types'

function useImage(url: string | null) { const [image, setImage] = useState<HTMLImageElement | null>(null); useEffect(() => { if (!url) { setImage(null); return } const img = new window.Image(); img.onload = () => setImage(img); img.src = url; return () => { img.onload = null } }, [url]); return image }
export function FloorPlanCanvas({ url, imageWidth, imageHeight, rooms, polygons, selectedRoomId, selectedPolygonId, draft, drawing, editable, onBackgroundClick, onSelectPolygon, onMovePoint }: { url: string | null; imageWidth: number; imageHeight: number; rooms: Room[]; polygons: RoomPolygon[]; selectedRoomId: string | null; selectedPolygonId: string | null; draft: Point[]; drawing: boolean; editable: boolean; onBackgroundClick?: (point: Point) => void; onSelectPolygon: (polygon: RoomPolygon) => void; onMovePoint?: (polygon: RoomPolygon, index: number, point: Point) => void }) {
  const parent = useRef<HTMLDivElement>(null); const stage = useRef<Konva.Stage>(null); const [width, setWidth] = useState(500); const image = useImage(url)
  useEffect(() => { if (!parent.current) return; const obs = new ResizeObserver(entries => setWidth(Math.max(1, entries[0].contentRect.width))); obs.observe(parent.current); return () => obs.disconnect() }, [])
  const ratio = imageWidth && imageHeight ? imageHeight / imageWidth : 0.72; const height = Math.max(180, width * ratio)
  const toPixels = (p: Point) => ({ x: p.x * width, y: p.y * height })
  const toNorm = (p: Point): Point => ({ x: Math.max(0, Math.min(1, p.x / width)), y: Math.max(0, Math.min(1, p.y / height)) })
  const addPoint = (targetClass: string) => { if (!drawing || !onBackgroundClick || !['Stage', 'Image'].includes(targetClass)) return; const point = stage.current?.getPointerPosition(); if (point) onBackgroundClick(toNorm(point)) }
  return <div ref={parent} className="w-full overflow-hidden rounded-xl bg-[#e7eee8]"><Stage ref={stage} width={width} height={height} onClick={e => addPoint(e.target.getClassName())} onTap={e => addPoint(e.target.getClassName())}><Layer>{image && <KonvaImage image={image} width={width} height={height} />}{polygons.map(poly => { const selected = selectedPolygonId === poly.id; const active = selectedRoomId === poly.room_id; const points = poly.points.flatMap(p => [p.x * width, p.y * height]); const center = poly.points.reduce((a, p) => ({ x: a.x + p.x / poly.points.length, y: a.y + p.y / poly.points.length }), { x: 0, y: 0 }); return <GroupPolygon key={poly.id} polygon={poly} points={points} center={toPixels(center)} label={rooms.find(r => r.id === poly.room_id)?.name || 'Room'} selected={selected} active={active} drawing={drawing} editable={editable} width={width} height={height} onSelect={() => onSelectPolygon(poly)} onMovePoint={onMovePoint} /> })}{draft.length > 0 && <><Line points={draft.flatMap(p => [p.x * width, p.y * height])} stroke="#ef9c68" strokeWidth={3} dash={[7, 5]}/>{draft.map((p, i) => <Circle key={i} x={p.x * width} y={p.y * height} radius={5} fill="#ef9c68" stroke="white" strokeWidth={2}/>)}</>}</Layer></Stage></div>
}
function GroupPolygon({ polygon, points, center, label, selected, active, drawing, editable, width, height, onSelect, onMovePoint }: { polygon: RoomPolygon; points: number[]; center: Point; label: string; selected: boolean; active: boolean; drawing: boolean; editable: boolean; width: number; height: number; onSelect: () => void; onMovePoint?: (poly: RoomPolygon, index: number, point: Point) => void }) { const color = active || selected ? '#205c57' : '#e9a772'; return <><Line points={points} closed fill={active || selected ? '#205c5755' : '#e9a77255'} stroke={color} strokeWidth={selected ? 3 : 2} onClick={e => { e.cancelBubble = true; if (!drawing) onSelect() }} onTap={() => { if (!drawing) onSelect() }} /><Text x={center.x - 45} y={center.y - 9} width={90} align="center" text={label} fontSize={Math.max(11, Math.min(16, width / 36))} fontStyle="bold" fill="white" shadowColor="#13292a" shadowBlur={7} listening={false}/>{selected && editable && !drawing && polygon.points.map((p, i) => <Circle key={i} x={p.x * width} y={p.y * height} radius={7} fill="white" stroke={color} strokeWidth={2} draggable dragBoundFunc={pos => ({ x: Math.max(0, Math.min(width, pos.x)), y: Math.max(0, Math.min(height, pos.y)) })} onDragEnd={e => onMovePoint?.(polygon, i, { x: e.target.x() / width, y: e.target.y() / height })} />)}</> }
