import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode, TextareaHTMLAttributes } from 'react'
import { Slot } from '@radix-ui/react-slot'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '../lib/utils'
export { cn }
const buttonStyles = cva('inline-flex items-center justify-center gap-2 rounded-xl font-semibold transition-colors disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-pine', { variants: { variant: { default: 'bg-pine text-white hover:bg-ink', outline: 'border border-line bg-white text-ink hover:bg-mint', ghost: 'text-ink hover:bg-mint', danger: 'bg-red-50 text-red-700 hover:bg-red-100' }, size: { default: 'h-11 px-5 text-sm', sm: 'h-9 px-3 text-sm', lg: 'h-12 px-6 text-sm', icon: 'h-10 w-10' } }, defaultVariants: { variant: 'default', size: 'default' } })
export function Button({ className, variant, size, asChild = false, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & VariantProps<typeof buttonStyles> & { asChild?: boolean }) { const Comp = asChild ? Slot : 'button'; return <Comp className={cn(buttonStyles({ variant, size }), className)} {...props} /> }
export function Input(props: InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className={cn('h-11 w-full rounded-xl border border-line bg-white px-3 text-sm text-ink placeholder:text-slate-400', props.className)} /> }
export function Textarea(props: TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea {...props} className={cn('min-h-28 w-full rounded-xl border border-line bg-white px-3 py-3 text-sm text-ink placeholder:text-slate-400', props.className)} /> }
export function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) { return <label className="block space-y-2"><span className="text-sm font-semibold text-ink">{label}</span>{children}{hint && <span className="block text-xs text-slate-500">{hint}</span>}</label> }
export function Card({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn('rounded-2xl border border-line bg-white p-6 shadow-card', className)}>{children}</div> }
export function Notice({ children, kind = 'error' }: { children: ReactNode; kind?: 'error' | 'success' | 'info' }) { return <div role="status" className={cn('rounded-xl px-4 py-3 text-sm', kind === 'error' ? 'bg-red-50 text-red-700' : kind === 'success' ? 'bg-emerald-50 text-emerald-800' : 'bg-mint text-pine')}>{children}</div> }
export function Spinner() { return <div aria-label="Loading" className="mx-auto h-8 w-8 animate-spin rounded-full border-[3px] border-pine/20 border-t-pine" /> }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) { return <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div>{eyebrow && <p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-pine">{eyebrow}</p>}<h1 className="text-3xl font-extrabold tracking-tight text-ink sm:text-4xl">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm text-slate-500">{description}</p>}</div>{action}</div> }
